- name: generate config for connection {{ item.key }}
  template: src=etc/swanctl/conf.d/site-to-site-psk.conf.j2 dest=/etc/swanctl/conf.d/{{ item.key }}.conf
  notify: restart strongswan
  tags:
    - config

- name: generate systemd service for XFRM interface ipsec_{{ item.key }}
  template: src=etc/systemd/system/xfrm-interface.service.j2 dest=/etc/systemd/system/xfrm-ipsec_{{ item.key }}.service
  tags:
    - config

- name: enable systemd service for XFRM interface ipsec_{{ item.key }}
  systemd: name=xfrm-ipsec_{{ item.key }}.service daemon_reload=true enabled=true

#- name: start systemd service for XFRM interface ipsec_{{ item.key }}
  #systemd: name=xfrm-ipsec_{{ item.key }}.service state=started
