- name: install package on system
  include_tasks: "{{ router_os_distribution }}-pkg.yml"

- name: enable strongswan service
  systemd: name=strongswan enabled=true

- name: generate config
  template: src={{ item }} dest=/{{ item | regex_replace('\.j2$', '') }}
  with_items:
    - etc/strongswan.d/charon-systemd.conf.j2

- name: ensure /etc/swanctl/updown dir exists
  file: path=/etc/swanctl/updown state=directory owner=root group=root mode="0755"

- name: generate strongswan Site-to-Site with PSK connection config
  include_tasks: connection-site-to-site-psk.yml
  loop: "{{ strongswan_site_to_site_psk_connections | dict2items }}"
  tags:
    - config
